#!/usr/bin/env python
"""
Submission interface for Gobblecube.
Consistent with the required signature and the hybrid training logic.
"""

from __future__ import annotations

import pickle
import math
from datetime import datetime
from pathlib import Path

# Path to the artifact generated by your training script
_MODEL_PATH = Path(__file__).parent / "model.pkl"

# Load model data once
with open(_MODEL_PATH, "rb") as _f:
    _MODEL_DATA = pickle.load(_f)

# Unpack artifacts
_LOOKUPS = _MODEL_DATA["lookups"]
_GLOBAL_MEDIAN = _LOOKUPS["global"]
_HOURLY_ZONE = _LOOKUPS["hourly_zone"]
_ZONE_ROUTE = _LOOKUPS["zone_route"]
_HOURLY_CLUSTER = _LOOKUPS["hourly_cluster"]
_CLUSTER_ROUTE = _LOOKUPS["cluster_route"]
_ROUTE_DAY_HOUR_FREQ = _LOOKUPS["route_day_hour_freq"]

_OSRM = _MODEL_DATA["osrm"]
_WEATHER = _MODEL_DATA["weather"]
_CLUSTER_MAPPING = _MODEL_DATA["cluster_mapping"]
_LGBM_MODEL = _MODEL_DATA["lgbm_model"]

def predict(request: dict) -> float:
    """
    Predicts trip duration in seconds.
    Matches the Gobblecube fixed signature.
    """
    # 1. Parse Input using Grader Keys
    pz = int(request["pickup_zone"])
    dz = int(request["dropoff_zone"])
    ts = datetime.fromisoformat(request["requested_at"])
    
    # Note: passenger_count is in request but ignored as it wasn't in training features
    
    # 2. Time Engineering
    hour = ts.hour
    dow = ts.weekday()
    month = ts.month
    is_weekend = 1 if dow >= 5 else 0
    week_of_year = ts.isocalendar()[1]
    week_of_month = (ts.day - 1) // 7 + 1
    time_of_day = hour // 6
    
    # 3. Cluster & Route Interaction
    pc = _CLUSTER_MAPPING.get(pz, -1)
    dc = _CLUSTER_MAPPING.get(dz, -1)
    cluster_route = ((pc + 1) * 100) + (dc + 1)
    
    # 4. Data Lookups (OSRM, Weather, Freq)
    osrm_route = _OSRM.get((pz, dz), {"osrm_time": math.nan, "osrm_distance": math.nan})
    osrm_time = float(osrm_route["osrm_time"])
    osrm_dist = float(osrm_route["osrm_distance"])
    
    route_day_hour_freq = float(_ROUTE_DAY_HOUR_FREQ.get((pz, dz, dow, hour), 0.0))
    
    # Match weather on hour and zone
    merge_hour = ts.replace(minute=0, second=0, microsecond=0)
    w = _WEATHER.get((merge_hour, pz), {})
    is_raining = int(w.get("is_raining", 0))
    is_snowing = int(w.get("is_snowing", 0))
    temp_c = float(w.get("temp_c", 12.0))
    windspeed_mps = float(w.get("windspeed_mps", 3.0))
    visibility_m = float(w.get("visibility_m", 16000.0))

    # 5. Fallback Median Cascade (base_pred) - FIXED OSRM TIER
    base_pred = _HOURLY_ZONE.get((pz, dz, hour))
    if base_pred is None:
        base_pred = _ZONE_ROUTE.get((pz, dz))
        if base_pred is None:
            base_pred = _HOURLY_CLUSTER.get((pc, dc, hour))
            if base_pred is None:
                base_pred = _CLUSTER_ROUTE.get((pc, dc))
                if base_pred is None:
                    # Use OSRM time if available, otherwise Global Median
                    base_pred = osrm_time if not math.isnan(osrm_time) else _GLOBAL_MEDIAN

    # 6. Construct Feature Vector (Order MUST match training script)
    # CATEGORICAL_FEATURES + NUMERIC_FEATURES
    row_values = [
        # Categorical
        pz, dz, hour, dow, month, is_weekend, week_of_year, 
        week_of_month, pc, dc, cluster_route, time_of_day, 
        is_raining, is_snowing,
        
        # Numeric
        osrm_time, 
        osrm_dist, 
        base_pred, 
        (base_pred - osrm_time) if not math.isnan(osrm_time) else math.nan, # FIXED NaN HANDLING
        temp_c, 
        windspeed_mps, 
        visibility_m, 
        route_day_hour_freq
    ]
    
    # 7. Model Inference
    # LightGBM returns the residual because we used init_score in training
    residual = _LGBM_MODEL.predict([row_values])[0]
    
    # Final Result = Median Baseline + Model Correction
    return max(1.0, float(base_pred + residual))